import 'package:flutter/material.dart';

final Map<String, Map<String, dynamic>> shoppingCategories = {
  '野菜': {
    'image': 'vegetable.png',
    'items': [
      {'name': '人参', 'image': 'ninjin_carrot.png'},
      {'name': 'ジャガイモ', 'image':'vegetable_maru_dansyaku.png'},
      {'name': '玉ねぎ', 'image':'tamanegi_onion (1).png'},
      {'name': 'ピーマン', 'image':'piman_greenpepper.png'},
      {'name': 'にら', 'image':'vegetable_nira.png'},
      {'name': 'トマト', 'image':'food_puchitomato.png'},
      {'name': 'キャベツ', 'image':'cut_vegetable_cabbage.png'},
      {'name': 'レタス','image':'vegetable_green_lettuce.png'},
      {'name': 'ほうれん草', 'image': 'hourensou_spinach.png'},
      {'name': 'ブロッコリー', 'image': 'broccoli.png'},
      {'name': 'カリフラワー', 'image': 'cauliflower.png'},
      {'name': 'ナス', 'image': 'vegetable_mizunasu.png'},
      {'name': 'キュウリ', 'image': 'kyuuri_cucumber.png'},
      {'name': 'パプリカ', 'image': 'paprika.png'},
      {'name': 'ゴボウ', 'image': 'vegetable_gobou.png'},
      {'name': 'レンコン', 'image': 'vegetable_renkon.png'},
      {'name': 'アスパラガス', 'image': 'asparagus.png'},
      {'name': 'ネギ', 'image': 'vegetable_negi.png'},
      {'name': 'サツマイモ', 'image': 'vegetable_satsumaimo_purple.png'},
      {'name': 'かぼちゃ', 'image': 'vegetable_kabocha.png'},
      {'name': '大根', 'image': 'daikon_radish.png'},
      {'name': 'しょうが', 'image': 'vegetable_syouga.png'},
      {'name': 'ミョウガ', 'image': 'vegetable_myouga.png'},
      {'name': 'ズッキーニ', 'image': 'vegetable_zucchini.png'},
      {'name': 'トウモロコシ', 'image': 'vegetable_toumorokoshi_corn_wagiri.png'},
      {'name': '枝豆', 'image': 'edamame.png'},
      {'name': '水菜', 'image': 'vegetable_mizuna.png'},
      {'name': 'チンゲン菜', 'image': 'vegetable_chingensai.png'},
      {'name': 'シソ', 'image': 'vegetable_shiso.png'},
      {'name': 'カブ','image': 'kabu_turnip.png'},
    ],
  },
  '果物': {
    'image': 'fruits_basket.png',
    'items': [
      {'name': 'りんご', 'image': 'fruit_ringo.png'},
      {'name': 'みかん', 'image': 'fruit_orange.png'},
      {'name': 'バナナ', 'image': 'fruit_banana.png'},
      {'name': 'ぶどう', 'image': 'fruit_budou_kyohou.png'},
      {'name': 'いちご', 'image': 'fruit_strawberry.png'},
      {'name': 'もも', 'image': 'fruit_momo.png'},
      {'name': 'さくらんぼ', 'image': 'fruit_cherry.png'},
      {'name': 'メロン', 'image': 'fruit_melon.png'},
      {'name': 'スイカ', 'image': 'fruit_suika_kodama.png'},
      {'name': 'パイナップル', 'image': 'fruit_pineapple.png'},
      {'name': 'キウイ', 'image': 'cut_fruit_kiwi.png'},
      {'name': 'マンゴー', 'image': 'fruit_mango.png'},
      {'name': 'パパイヤ', 'image': 'fruit_papaya.png'},
      {'name': 'ブルーベリー', 'image': 'fruit_blueberry.png'},
      {'name': 'ラズベリー', 'image': 'fruit_raspberry_heta.png'},
      {'name': 'カシス', 'image': 'fruit_cassis.png'},
      {'name': 'レモン', 'image': 'fruit_lemon.png'},
      {'name': 'ライム', 'image': 'fruit_lime_slice.png'},
      {'name': 'グレープフルーツ', 'image': 'fruit_slice_grapefruit.png'},
      {'name': 'アボカド', 'image': 'cut_vegetable_avocado.png'},
      {'name': '柿', 'image': 'fruit_kaki.png'},
      {'name': '梨', 'image': 'fruit_nashi.png'},
      {'name': 'びわ', 'image': 'fruit_biwa.png'},
      {'name': 'ドリアン', 'image': 'fruit_durian.png'},
      {'name': 'スターフルーツ', 'image': 'fruit_starfruit.png'},
      {'name': 'ドラゴンフルーツ', 'image': 'fruit_dragonfruit.png'},
      {'name': 'ザクロ', 'image': 'fruit_pomegranate.png'},
      {'name': 'イチジク', 'image': 'fruit_ichijiku.png'},
    ],
  },
  'きのこ': {
    'image': 'kinoko.png',
    'items': [
      {'name': 'しいたけ', 'image': 'kinoko_shiitake.png'},
      {'name': 'えのき', 'image':'kinoko_enoki.png'},
      {'name': 'しめじ', 'image':'kinoko_shimeji.png'},
      {'name': 'まいたけ', 'image':'kinoko_maitake.png'},
      {'name': 'エリンギ', 'image':'kinoko_eringi.png'},
      {'name': 'マッシュルーム', 'image':'vegetable_mushroom.png'},
    ],
  },
  '肉類': {
    'image': 'food_niku_pack.png',
    'items': [
      {'name': '牛肉（肩ロース）', 'image': 'niku_gyu.png'},
      {'name': '牛肉（サーロイン）', 'image': 'food_niku_gyuniku_steak.png'},
      {'name': '牛肉（ヒレ）', 'image': 'niku_gyu.png'},
      {'name': '牛肉（バラ）', 'image': 'niku_gyu.png'},
      {'name': '牛肉（もも）', 'image': 'niku_gyu.png'},
      {'name': '豚肉（肩ロース）', 'image': 'food_niku_buta_ro-su.png'},
      {'name': '豚肉（バラ）', 'image': 'niku_buta.png'},
      {'name': '豚肉（ヒレ）', 'image': 'niku_buta.png'},
      {'name': '豚肉（もも）', 'image': 'niku_buta.png'},
      {'name': '鶏肉（胸肉）', 'image': 'niku_tori.png'},
      {'name': '鶏肉（もも肉）', 'image': 'niku_tori.png'},
      {'name': '鶏肉（ささみ）', 'image': 'food_niku_tori_sasami.png'},
      {'name': '鶏肉（手羽元）', 'image': 'food_chicken_tebamoto_nama.png'},
      {'name': '鶏肉（手羽先）', 'image': 'food_chicken_tebasaki_nama.png'},
      {'name': 'ミンチ（牛肉）', 'image': 'food_hikiniku_beef.png'},
      {'name': 'ミンチ（豚肉）', 'image': 'food_hikiniku_pork.png'},
      {'name': 'ミンチ（鶏肉）', 'image': 'food_hikiniku_checken.png'},
      {'name': 'ミンチ（合い挽き）', 'image': 'food_hikiniku_pork.png'},
      {'name': 'ベーコン', 'image': 'kunsei_bacon.png'},
      {'name': 'ソーセージ', 'image': 'kunsei_souseiji.png'},
      {'name': 'ハム', 'image': 'kunsei_ham.png'},
    ],
  },
  '麺類': {
    'image': 'bukkake_udon.png',
    'items': [
      {'name': 'うどん', 'icon': Icons.rice_bowl},
      {'name': 'そば', 'icon': Icons.lunch_dining},
      {'name': 'ラーメン', 'icon': Icons.restaurant},
      {'name': 'パスタ', 'icon': Icons.food_bank},
      {'name': '焼きそば', 'icon': Icons.fireplace},
      {'name': '素麺', 'icon': Icons.waves},
      {'name': 'フォー', 'icon': Icons.public},
      {'name': '春雨', 'icon': Icons.cloud},
    ],
  },
  '乳製品': {
    'image': 'character_milk_ushi.png',
    'items': [
      {'name': '牛乳', 'icon': Icons.local_drink},
      {'name': 'ヨーグルト', 'icon': Icons.icecream},
      {'name': 'バター', 'icon': Icons.cake},
      {'name': 'チーズ（スライス）', 'icon': Icons.fastfood},
      {'name': 'チーズ（ブロック）', 'icon': Icons.dangerous_rounded},
      {'name': 'チーズ（粉）', 'icon': Icons.ramen_dining},
      {'name': '生クリーム', 'icon': Icons.coffee},
{'name': 'クリームチーズ', 'icon': Icons.emoji_food_beverage},
{'name': 'カッテージチーズ', 'icon': Icons.breakfast_dining},
{'name': 'モッツァレラチーズ', 'icon': Icons.egg},
{'name': 'ゴーダチーズ', 'icon': Icons.emoji_food_beverage},
{'name': 'ブルーチーズ', 'icon': Icons.brunch_dining},
{'name': 'ヨーグルトドリンク', 'icon': Icons.local_bar},
{'name': 'ホイップクリーム', 'icon': Icons.cloud},
{'name': '練乳', 'icon': Icons.bubble_chart},
{'name': 'アイスクリーム', 'icon': Icons.ac_unit},
{'name': 'スキムミルク', 'icon': Icons.grass},
{'name': 'プロセスチーズ', 'icon': Icons.cut},
],
},
  '魚介類': {
    'image': 'fish_buri2.png',
    'items': [
      {'name': 'サーモン', 'icon': Icons.water},
      {'name': 'エビ', 'icon': Icons.water_damage},
      {'name': 'タコ', 'icon': Icons.water},
      {'name': 'イカ', 'icon': Icons.sailing},
      {'name': 'カニ', 'icon': Icons.dinner_dining},
      {'name': 'アジ', 'icon': Icons.face},
      {'name': 'イワシ', 'icon': Icons.ramen_dining},
      {'name': 'サバ', 'icon': Icons.local_pizza},
      {'name': 'タイ', 'icon': Icons.emoji_food_beverage},
      {'name': 'ヒラメ', 'icon': Icons.park},
      {'name': 'カレイ', 'icon': Icons.landscape},
      {'name': 'フグ', 'icon': Icons.warning_amber},
      {'name': 'カツオ', 'icon': Icons.local_florist},
      {'name': 'マグロ', 'icon': Icons.cut},
      {'name': 'ブリ', 'icon': Icons.spa},
      {'name': 'サンマ', 'icon': Icons.line_weight},
      {'name': 'ホタテ', 'icon': Icons.casino},
      {'name': 'アワビ', 'icon': Icons.star},
      {'name': 'サザエ', 'icon': Icons.circle},
      {'name': 'ハマグリ', 'icon': Icons.brightness_1},
      {'name': 'シジミ', 'icon': Icons.bubble_chart},
      {'name': 'アサリ', 'icon': Icons.flare},
      {'name': 'カキ', 'icon': Icons.local_dining},
      {'name': 'ニシン', 'icon': Icons.arrow_circle_down},
      {'name': 'シャコ', 'icon': Icons.restaurant},
      {'name': 'ミル貝', 'icon': Icons.eco},
      {'name': 'トリガイ', 'icon': Icons.circle_notifications},
      {'name': 'メバル', 'icon': Icons.ac_unit},
      {'name': 'タラ', 'icon': Icons.cloud},
      {'name': 'シラウオ', 'icon': Icons.waves},
      {'name': 'ハタハタ', 'icon': Icons.water_drop},
      {'name': 'キンメダイ', 'icon': Icons.shield},
      {'name': 'クロダイ', 'icon': Icons.waterfall_chart},
      {'name': 'メジマグロ', 'icon': Icons.blender},
      {'name': 'ヤリイカ', 'icon': Icons.sailing},
      {'name': 'ホッケ', 'icon': Icons.toll},
      {'name': 'ノドグロ', 'icon': Icons.label},
      {'name': 'サワラ', 'icon': Icons.dock},
      {'name': 'ハモ', 'icon': Icons.settings},
    ],
  },
  '調味料': {
    'image': 'thumbnail_cooking_bittersbottle.png',
    'items': [
      {'name': '塩', 'icon': Icons.kitchen_rounded},
      {'name': '砂糖', 'icon': Icons.cookie},
      {'name': '醤油', 'icon': Icons.kitchen},
      {'name': '酢', 'icon': Icons.local_cafe},
      {'name': 'みりん', 'icon': Icons.emoji_food_beverage},
      {'name': '味噌', 'icon': Icons.ramen_dining},
      {'name': 'ポン酢', 'icon': Icons.spa},
      {'name': 'ケチャップ', 'icon': Icons.local_pizza},
      {'name': 'マヨネーズ', 'icon': Icons.breakfast_dining},
      {'name': '中濃ソース', 'icon': Icons.water},
      {'name': 'ウスターソース', 'icon': Icons.sports_bar},
      {'name': 'ごま油', 'icon': Icons.grass},
      {'name': 'オリーブオイル', 'icon': Icons.eco},
      {'name': 'サラダ油', 'icon': Icons.format_paint},
      {'name': 'はちみつ', 'icon': Icons.bubble_chart},
      {'name': 'バルサミコ酢', 'icon': Icons.wine_bar},
      {'name': 'カレー粉', 'icon': Icons.stacked_bar_chart},
      {'name': '七味唐辛子', 'icon': Icons.fireplace},
      {'name': 'こしょう', 'icon': Icons.whatshot},
      {'name': 'だしの素', 'icon': Icons.lunch_dining},
    ],
  },
  '飲み物': {
    'image': 'thumbnail_drink_bin_bottle.png',
    'items': [
      {'name': '水', 'icon': Icons.water_drop},
      {'name': 'ジュース', 'icon': Icons.local_drink},
      {'name': 'コーヒー', 'icon': Icons.coffee},
      {'name': 'お茶', 'icon': Icons.emoji_food_beverage},
      {'name': '紅茶', 'icon': Icons.emoji_food_beverage},
      {'name': '緑茶', 'icon': Icons.local_florist},
      {'name': 'ウーロン茶', 'icon': Icons.spa},
      {'name': 'ほうじ茶', 'icon': Icons.ramen_dining},
      {'name': '麦茶', 'icon': Icons.grass},
      {'name': 'ココア', 'icon': Icons.cake},
      {'name': '炭酸水', 'icon': Icons.bubble_chart},
      {'name': 'エナジードリンク', 'icon': Icons.flash_on},
      {'name': 'スポーツドリンク', 'icon': Icons.sports_handball},
      {'name': 'ビール', 'icon': Icons.sports_bar},
      {'name': '日本酒', 'icon': Icons.local_bar},
      {'name': '焼酎', 'icon': Icons.wine_bar},
      {'name': 'ワイン', 'icon': Icons.wine_bar},
      {'name': 'シャンパン', 'icon': Icons.star},
      {'name': 'ウイスキー', 'icon': Icons.nightlife},
      {'name': 'カクテル', 'icon': Icons.tapas},
      {'name': 'ラムネ', 'icon': Icons.bubble_chart},
      {'name': '甘酒', 'icon': Icons.local_cafe},
      {'name': 'ミルクティー', 'icon': Icons.coffee},
      {'name': 'レモネード', 'icon': Icons.sunny},
      {'name': 'アイスコーヒー', 'icon': Icons.ac_unit},
      {'name': 'ホットコーヒー', 'icon': Icons.fireplace},
      {'name': 'フルーツジュース', 'icon': Icons.local_pizza},
      {'name': 'スムージー', 'icon': Icons.blender},
      {'name': 'プロテインドリンク', 'icon': Icons.fitness_center},
    ],
  },
  'お菓子': {
    'image': 'icecream.png',
    'items': [
      {'name': 'クッキー', 'icon': Icons.cookie},
      {'name': 'キャンディー', 'icon': Icons.emoji_food_beverage},
      {'name': 'チョコレート', 'icon': Icons.cake},
      {'name': 'ポテトチップス', 'icon': Icons.fastfood},
      {'name': 'プリッツ', 'icon': Icons.straight},
      {'name': 'ポッキー', 'icon': Icons.short_text},
      {'name': 'せんべい', 'icon': Icons.rice_bowl},
      {'name': '大福', 'icon': Icons.circle},
      {'name': 'どら焼き', 'icon': Icons.lunch_dining},
      {'name': 'たい焼き', 'icon': Icons.water},
      {'name': 'ワッフル', 'icon': Icons.grid_on},
      {'name': 'ドーナツ', 'icon': Icons.donut_large},
      {'name': 'マカロン', 'icon': Icons.cloud},
      {'name': 'ショートケーキ', 'icon': Icons.cake},
      {'name': 'ミルフィーユ', 'icon': Icons.layers},
      {'name': 'シュークリーム', 'icon': Icons.emoji_food_beverage},
      {'name': 'アイスクリーム', 'icon': Icons.ac_unit},
      {'name': 'パフェ', 'icon': Icons.icecream},
      {'name': 'ゼリー', 'icon': Icons.bubble_chart},
      {'name': 'プリン', 'icon': Icons.egg},
      {'name': 'お団子', 'icon': Icons.brightness_1},
      {'name': 'たい焼き', 'icon': Icons.waves},
      {'name': '羊羹', 'icon': Icons.crop_landscape},
      {'name': '和三盆', 'icon': Icons.star},
      {'name': 'ポップコーン', 'icon': Icons.local_movies},
      {'name': 'キャラメル', 'icon': Icons.grass},
      {'name': 'グミ', 'icon': Icons.emoji_nature},
      {'name': 'チューインガム', 'icon': Icons.comment},
      {'name': 'チョコレートバー', 'icon': Icons.bakery_dining},
      {'name': 'フィナンシェ', 'icon': Icons.card_giftcard},
    ],
  },
  '日用品': {
    'image': 'nichiyouhin.png',
    'items': [
      {'name': 'トイレットペーパー', 'icon': Icons.receipt},
      {'name': 'ティッシュ', 'icon': Icons.local_laundry_service},
      {'name': '洗剤', 'icon': Icons.local_drink},
      {'name': 'シャンプー', 'icon': Icons.shower},
      {'name': 'ボディソープ', 'icon': Icons.bubble_chart},
      {'name': '歯磨き粉', 'icon': Icons.brush},
      {'name': 'カミソリ', 'icon': Icons.cut},
      {'name': 'ハンドソープ', 'icon': Icons.soap},
    ],
  },
  '文房具': {
    'image': 'pen_fudebako.png',
    'items': [
      {'name': 'ノート', 'icon': Icons.book},
      {'name': '鉛筆', 'icon': Icons.edit},
      {'name': 'ボールペン', 'icon': Icons.create},
      {'name': '消しゴム', 'icon': Icons.crop_square},
      {'name': '定規', 'icon': Icons.straighten},
      {'name': 'ハサミ', 'icon': Icons.content_cut},
      {'name': 'のり', 'icon': Icons.paste},
      {'name': '付箋', 'icon': Icons.sticky_note_2},
    ],
  },
};
